#!/usr/bin/env python3
"""Regenerate the README's language and topic summary from the problem folders.

Topic tags come from LeetCode's public GraphQL API and are cached in
scripts/topics_cache.json, so a run only fetches problems it has not seen
before. If the API is unreachable, cached data is used and the run still
succeeds -- it just skips any problem that is both new and unfetchable.

Usage: python3 scripts/update_topics.py [--check]
  --check  exit 1 if README.md would change, without writing it
"""

import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, "scripts", "topics_cache.json")
README = os.path.join(ROOT, "README.md")

START = "<!-- AUTO-TOPICS:START -->"
END = "<!-- AUTO-TOPICS:END -->"

EXT_LANG = {".go": "Go", ".cpp": "C++", ".cc": "C++", ".c": "C",
            ".py": "Python", ".java": "Java", ".js": "JavaScript",
            ".ts": "TypeScript", ".rs": "Rust", ".kt": "Kotlin"}

QUERY = ("query q($t:String!){question(titleSlug:$t)"
         "{questionFrontendId difficulty topicTags{name}}}")


def problem_dirs():
    return sorted(d for d in os.listdir(ROOT)
                  if re.match(r"^\d{4}-", d) and os.path.isdir(os.path.join(ROOT, d)))


def languages_in(d):
    langs = set()
    for f in os.listdir(os.path.join(ROOT, d)):
        ext = os.path.splitext(f)[1].lower()
        if ext in EXT_LANG:
            langs.add(EXT_LANG[ext])
    return langs


def load_cache():
    try:
        with open(CACHE) as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return {}


def fetch(slug):
    body = json.dumps({"query": QUERY, "variables": {"t": slug}}).encode()
    req = urllib.request.Request(
        "https://leetcode.com/graphql", data=body, method="POST",
        headers={"Content-Type": "application/json",
                 "User-Agent": "Mozilla/5.0 (readme-topic-sync)"})
    with urllib.request.urlopen(req, timeout=20) as r:
        q = json.load(r)["data"]["question"]
    if not q:
        raise ValueError("no question data for " + slug)
    return {"difficulty": q["difficulty"],
            "topics": [t["name"] for t in q["topicTags"]]}


def main():
    check_only = "--check" in sys.argv
    cache = load_cache()
    dirs = problem_dirs()

    missing = [d for d in dirs if d[5:] not in cache]
    if missing:
        print(f"fetching {len(missing)} new problem(s) from LeetCode...")
    for i, d in enumerate(missing):
        slug = d[5:]
        try:
            cache[slug] = fetch(slug)
            print(f"  + {slug}: {', '.join(cache[slug]['topics']) or '(no tags)'}")
        except (urllib.error.URLError, ValueError, KeyError, TimeoutError) as e:
            print(f"  ! {slug}: skipped ({e})", file=sys.stderr)
        if i < len(missing) - 1:
            time.sleep(1)  # be polite to the API

    # A problem carries several LeetCode tags and belongs under all of them,
    # so counts here overlap by design and deliberately do not sum to the total.
    by_topic = defaultdict(list)
    lang_totals = Counter()
    difficulty = Counter()
    untagged = []
    for d in dirs:
        slug = d[5:]
        langs = languages_in(d)
        for l in langs:
            lang_totals[l] += 1
        info = cache.get(slug)
        if not info or not info["topics"]:
            untagged.append(d)
            continue
        difficulty[info["difficulty"]] += 1
        for topic in info["topics"]:
            by_topic[topic].append((d, langs))

    rows = sorted(by_topic.items(), key=lambda kv: (-len(kv[1]), kv[0]))
    summary = f"**{len(dirs)} problems solved**"
    if lang_totals:
        summary += " — " + ", ".join(f"{n} in {l}" for l, n in lang_totals.most_common())
    diff_order = [d for d in ("Easy", "Medium", "Hard") if difficulty[d]]
    if diff_order:
        summary += "  \n" + " · ".join(f"{difficulty[d]} {d}" for d in diff_order)

    lines = [START, "", summary, "",
             "| Topic | Problems | Languages |",
             "| --- | ---: | --- |"]
    for topic, entries in rows:
        langs = sorted({l for _, ls in entries for l in ls})
        lines.append(f"| {topic} | {len(entries)} | {', '.join(langs) or '—'} |")
    if untagged:
        lines.append(f"| _(untagged)_ | {len(untagged)} | — |")
    lines += ["",
              "<sub>Generated by `scripts/update_topics.py` from LeetCode's topic tags. "
              "A problem carries several tags, so the counts overlap and do not sum to the "
              "total.</sub>",
              "", END]
    block = "\n".join(lines)

    with open(README, encoding="utf-8") as fh:
        text = fh.read()
    if START in text and END in text:
        new = text[:text.index(START)] + block + text[text.index(END) + len(END):]
    else:
        print("markers not found in README.md", file=sys.stderr)
        return 1

    if new == text:
        print("README.md already up to date")
        return 0
    if check_only:
        print("README.md is out of date (run without --check to update)")
        return 1

    with open(README, "w", encoding="utf-8") as fh:
        fh.write(new)
    os.makedirs(os.path.dirname(CACHE), exist_ok=True)
    with open(CACHE, "w", encoding="utf-8") as fh:
        json.dump(cache, fh, indent=1, sort_keys=True)
        fh.write("\n")
    print(f"README.md updated ({len(dirs)} problems, {len(rows)} topics)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
